# Project configuration
spring:
  application:
    name: OnlineShop

  # JPA configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: user
    password: 123
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_updates: true
        order_inserts: true
        format_sql: true
        generate_statistics: true
        default_schema: postgres

  # Flyway configuration
  flyway:
    baseline-on-migrate: true
    enabled: true
    validate-on-migrate: true
    baseline-version: 0
    schemas: postgres

  # Email configuration
  mail:
    host: smtp.example.com
    port: 587
    username: hello@google.com
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# External configuration
payment:
  gateway: mock
  currency: USD
  min-amount: 10.00

# Tomcat configuration
server:
  port: 8080


